import type { Metadata } from "next";
// import { GeistSans, GeistMono } from "next/font/google";
// OR
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ToastContainer from "../components/Toast";
import ServerStatus from "@/components/ServerStatus";
import AuthGuard from "@/components/AuthGuard";
import TimeTracker from "@/components/TimeTracker";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthGuard>
          <ServerStatus />
          <ToastContainer />
          <TimeTracker />
          {children}
        </AuthGuard>
      </body>
    </html>
  );
}
